version: "3.9"

services:
  backend:
    command: ["uvicorn", "api:app", "--app-dir", "backend", "--host", "0.0.0.0", "--port", "8093", "--reload"]
    volumes:
      - ./:/app
  frontend:
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8093
